src/Projeto.Curso.Core.Site/Areas/Cadastros/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Projeto.Curso.Core.Application.Pedido.Interfaces;
using Projeto.Curso.Core.Application.Pedido.ViewModels;
using Projeto.Curso.Core.Application.Shared.Intefaces;

namespace Projeto.Curso.Core.Site.Areas.Cadastros.Controllers
{
    [Area("Cadastros")]
    public class ClientesController : CadastroBaseController
    {

        private readonly IApplicationClientes appclientes;
        private readonly IApplicationShared appshared;

        public ClientesController(IApplicationClientes _appclientes,
                                  IApplicationShared _appshared)
        {
            appclientes = _appclientes;
            appshared = _appshared;
        }
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult ListagemClientesJson()
        {
            var lista = appclientes.ObterTodos();
            var settings = new JsonSerializerSettings();
            return Json(lista, settings);
        }

        public IActionResult Incluir()
        {
            ViewBag.ListaEstados = appshared.ObterEstados();
            return View();
        }

        [HttpPost]
        public IActionResult Incluir(ClientesViewModel model)
        {
            ViewBag.ListaEstados = appshared.ObterEstados();
            if (!ModelState.IsValid) return View();
            var cliente = appclientes.Adicionar(model);
            ViewBag.RetornoPost = "success,Cliente incluído com sucesso!";
            if (VerificaErros(cliente.ListaErros))
            {
                ViewBag.RetornoPost = "error,Não foi possível incluir o cliente!";
            }
            return View(model);
        }
    }
}

src/Projeto.Curso.Core.Site/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Projeto.Curso.Core.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (ViewBag.ListaErros != null)
            {

                foreach (var item in ViewBag.ListaErros)
                {
                    ViewData.ModelState.AddModelError(string.Empty, item);
                }
            }
            return View();
        }

    }
}

src/Projeto.Curso.Core.Site/Areas/Cadastros/Views/Clientes/Incluir.cshtml
@model Projeto.Curso.Core.Application.Pedido.ViewModels.ClientesViewModel

@{
    ViewData["Title"] = "Clientes - Inclusão";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row margem-top-10">
    <div class="col-md-12">
        <vc:summary />
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="glyphicon glyphicon-plus"></i>
                <strong>CLIENTES - INCLUSÃO</strong>
            </div>
            <div class="panel-body padding-25">
                <div class="row">
                    <form asp-action="Incluir">
                        @Html.Partial("_FormClientes")
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Html.Partial("_ValidationScriptsPartial");
    @if (@ViewBag.RetornoPost != "" && @ViewBag.RetornoPost != null)
    {
        var notificacao = ViewBag.RetornoPost.Split(',');
        <script>
            ExibeMensagem("@notificacao[0]", "@notificacao[1]");
            var limpa = "@notificacao[0]";
            if (limpa == 'success') {
               clearForm();
                $("#Apelido").focus();
            }
        </script>
    }

}

src/Projeto.Curso.Core.Site/Areas/Cadastros/Views/Clientes/Index.cshtml
@{
    ViewData["Title"] = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_Aguarde")


<div class="row margem-top-10">
    <div class="col-md-12">
        <a asp-area="Cadastros" onclick="return LigaAguarde()" asp-controller="Clientes" asp-action="Incluir" class="btn btn-ar btn-primary pull-left"><i class="glyphicon glyphicon-plus"></i> Novo Cliente</a>
    </div>
</div>

<div class="row margem-top-10">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="glyphicon glyphicon-list-alt"></i>
                LISTATEM CLIENTES
            </div>
            <div class="panel-body">
                <table id="tbgrid" class="table table-hover table-bordered tabela-cor">
                    <thead>
                        <tr>
                            <th class="no-sort"></th>
                            <th class="no-sort"></th>
                            <th class="no-sort"></th>
                            <th class="text-center">Id</th>
                            <th class="text-center">Apelido</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">CPF/CNPJ</th>
                            <th class="text-center">E-Mail</th>
                        </tr>
                    </thead>
                </table>

            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script>
        colunas = [
            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-info btn-sm showhint' title='Alterar registro'><i class='glyphicon glyphicon-search'></i></a>"
                }
            },

            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-primary btn-sm showhint' title='Alterar registro'><i class='glyphicon glyphicon-pencil'></i></a>"
                }
            },

            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-danger btn-sm showhint' title='Excluir registro'><i class='glyphicon glyphicon-trash'></i></a>"
                }
            },

            {
                "data": "Id",
                "width": "2%",
                "sClass": "text-center"
            },

            {
                "data": "Apelido",
                "width": "28%",
                "sClass": "text-left"
            },

            {
                "data": "Nome",
                "width": "40%",
                "sClass": "text-left"
            },

            {
                "data": "CpfCnpj",
                "width": "16%",
                "sClass": "text-left"
            },

            {
                "data": "Email",
                "width": "20%",
                "sClass": "text-left"
            }

        ];

        $(document).ready(function () {
            ListagemConsulta("tbgrid", urlClientes, colunas)
        });

    </script>

}

src/Projeto.Curso.Core.Site/Areas/Cadastros/Views/Clientes/_formClientes.cshtml
@model Projeto.Curso.Core.Application.Pedido.ViewModels.ClientesViewModel

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Apelido" class="control-label"></label>
            <input asp-for="Apelido" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Apelido" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
    </div>

</div>


<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="CpfCnpj" class="control-label"></label>
            <input asp-for="CpfCnpj" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="CpfCnpj" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label asp-for="Endereco" class="control-label"></label>
            <input asp-for="Endereco" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Endereco" class="text-danger"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Bairro" class="control-label"></label>
            <input asp-for="Bairro" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Bairro" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Cidade" class="control-label"></label>
            <input asp-for="Cidade" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="Cidade" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-group">
            <label asp-for="UF" class="control-label"></label>
            <select autocomplete="off" asp-for="UF" asp-items="@ViewBag.ListaEstados" class="form-control"></select>
            <span asp-validation-for="UF" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-group">
            <label asp-for="CEP" class="control-label"></label>
            <input asp-for="CEP" class="form-control limpa" autocomplete="off"  />
            <span asp-validation-for="CEP" class="text-danger"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-block btn-success"><i class="glyphicon glyphicon-floppy-disk"></i> Gravar</button>
    </div>

    <div class="col-md-2">
        <a asp-area="Cadastros" onclick="return LigaAguarde()" asp-controller="Clientes" asp-action="Index" class="btn btn-block btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Voltar</a>
    </div>
</div>